service: euthanasia
servers:
  - https://euthanasia-xq9o.onrender.com
registry:
  username: syuabr
  password:
    - KAMAL_REGISTRY_PASSWORD
builder:
  arch: amd64
env:
  secret:
    - RAILS_MASTER_KEY
proxy:
  ssl: false
  host: https://euthanasia-xq9o.onrender.com